package com.springapp.model.database;

import java.util.Date;

public class Candidate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidate.id
     *
     * @mbggenerated Thu Sep 03 08:56:17 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidate.day
     *
     * @mbggenerated Thu Sep 03 08:56:17 CST 2015
     */
    private Date day;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidate.code
     *
     * @mbggenerated Thu Sep 03 08:56:17 CST 2015
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidate.zs
     *
     * @mbggenerated Thu Sep 03 08:56:17 CST 2015
     */
    private Long zs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidate.rate
     *
     * @mbggenerated Thu Sep 03 08:56:17 CST 2015
     */
    private Double rate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidate.percent
     *
     * @mbggenerated Thu Sep 03 08:56:17 CST 2015
     */
    private Double percent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidate.prevs
     *
     * @mbggenerated Thu Sep 03 08:56:17 CST 2015
     */
    private Long prevs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidate.endp
     *
     * @mbggenerated Thu Sep 03 08:56:17 CST 2015
     */
    private Double endp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column candidate.decrease
     *
     * @mbggenerated Thu Sep 03 08:56:17 CST 2015
     */
    private Double decrease;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column candidate.id
     *
     * @return the value of candidate.id
     *
     * @mbggenerated Thu Sep 03 08:56:17 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column candidate.id
     *
     * @param id the value for candidate.id
     *
     * @mbggenerated Thu Sep 03 08:56:17 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column candidate.day
     *
     * @return the value of candidate.day
     *
     * @mbggenerated Thu Sep 03 08:56:17 CST 2015
     */
    public Date getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column candidate.day
     *
     * @param day the value for candidate.day
     *
     * @mbggenerated Thu Sep 03 08:56:17 CST 2015
     */
    public void setDay(Date day) {
        this.day = day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column candidate.code
     *
     * @return the value of candidate.code
     *
     * @mbggenerated Thu Sep 03 08:56:17 CST 2015
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column candidate.code
     *
     * @param code the value for candidate.code
     *
     * @mbggenerated Thu Sep 03 08:56:17 CST 2015
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column candidate.zs
     *
     * @return the value of candidate.zs
     *
     * @mbggenerated Thu Sep 03 08:56:17 CST 2015
     */
    public Long getZs() {
        return zs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column candidate.zs
     *
     * @param zs the value for candidate.zs
     *
     * @mbggenerated Thu Sep 03 08:56:17 CST 2015
     */
    public void setZs(Long zs) {
        this.zs = zs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column candidate.rate
     *
     * @return the value of candidate.rate
     *
     * @mbggenerated Thu Sep 03 08:56:17 CST 2015
     */
    public Double getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column candidate.rate
     *
     * @param rate the value for candidate.rate
     *
     * @mbggenerated Thu Sep 03 08:56:17 CST 2015
     */
    public void setRate(Double rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column candidate.percent
     *
     * @return the value of candidate.percent
     *
     * @mbggenerated Thu Sep 03 08:56:17 CST 2015
     */
    public Double getPercent() {
        return percent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column candidate.percent
     *
     * @param percent the value for candidate.percent
     *
     * @mbggenerated Thu Sep 03 08:56:17 CST 2015
     */
    public void setPercent(Double percent) {
        this.percent = percent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column candidate.prevs
     *
     * @return the value of candidate.prevs
     *
     * @mbggenerated Thu Sep 03 08:56:17 CST 2015
     */
    public Long getPrevs() {
        return prevs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column candidate.prevs
     *
     * @param prevs the value for candidate.prevs
     *
     * @mbggenerated Thu Sep 03 08:56:17 CST 2015
     */
    public void setPrevs(Long prevs) {
        this.prevs = prevs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column candidate.endp
     *
     * @return the value of candidate.endp
     *
     * @mbggenerated Thu Sep 03 08:56:17 CST 2015
     */
    public Double getEndp() {
        return endp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column candidate.endp
     *
     * @param endp the value for candidate.endp
     *
     * @mbggenerated Thu Sep 03 08:56:17 CST 2015
     */
    public void setEndp(Double endp) {
        this.endp = endp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column candidate.decrease
     *
     * @return the value of candidate.decrease
     *
     * @mbggenerated Thu Sep 03 08:56:17 CST 2015
     */
    public Double getDecrease() {
        return decrease;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column candidate.decrease
     *
     * @param decrease the value for candidate.decrease
     *
     * @mbggenerated Thu Sep 03 08:56:17 CST 2015
     */
    public void setDecrease(Double decrease) {
        this.decrease = decrease;
    }
}