package com.springapp.model.database;

import java.util.Date;

public class Morningp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column morningp.id
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column morningp.code
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column morningp.day
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    private Date day;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column morningp.startp
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    private Double startp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column morningp.lastp
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    private Double lastp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column morningp.curp
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    private Double curp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column morningp.highp
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    private Double highp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column morningp.lowp
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    private Double lowp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column morningp.curbuyp
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    private Double curbuyp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column morningp.curslp
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    private Double curslp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column morningp.curzs
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    private Long curzs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column morningp.curamount
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    private Double curamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column morningp.byonesh
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    private Long byonesh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column morningp.byonep
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    private Double byonep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column morningp.bytwosh
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    private Long bytwosh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column morningp.bytwop
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    private Double bytwop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column morningp.bythreesh
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    private Long bythreesh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column morningp.bythreep
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    private Double bythreep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column morningp.byfoursh
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    private Long byfoursh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column morningp.byfourp
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    private Double byfourp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column morningp.byfivesh
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    private Long byfivesh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column morningp.byfivep
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    private Double byfivep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column morningp.slonesh
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    private Long slonesh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column morningp.slonep
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    private Double slonep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column morningp.sltwosh
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    private Long sltwosh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column morningp.sltwop
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    private Double sltwop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column morningp.slthreesh
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    private Long slthreesh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column morningp.slthreep
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    private Double slthreep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column morningp.slfoursh
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    private Long slfoursh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column morningp.slfourp
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    private Double slfourp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column morningp.slfivesh
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    private Long slfivesh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column morningp.slfivep
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    private Double slfivep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column morningp.rate
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    private Double rate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column morningp.zs
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    private Long zs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column morningp.hang
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    private Boolean hang;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column morningp.id
     *
     * @return the value of morningp.id
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column morningp.id
     *
     * @param id the value for morningp.id
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column morningp.code
     *
     * @return the value of morningp.code
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column morningp.code
     *
     * @param code the value for morningp.code
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column morningp.day
     *
     * @return the value of morningp.day
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public Date getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column morningp.day
     *
     * @param day the value for morningp.day
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public void setDay(Date day) {
        this.day = day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column morningp.startp
     *
     * @return the value of morningp.startp
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public Double getStartp() {
        return startp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column morningp.startp
     *
     * @param startp the value for morningp.startp
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public void setStartp(Double startp) {
        this.startp = startp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column morningp.lastp
     *
     * @return the value of morningp.lastp
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public Double getLastp() {
        return lastp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column morningp.lastp
     *
     * @param lastp the value for morningp.lastp
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public void setLastp(Double lastp) {
        this.lastp = lastp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column morningp.curp
     *
     * @return the value of morningp.curp
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public Double getCurp() {
        return curp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column morningp.curp
     *
     * @param curp the value for morningp.curp
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public void setCurp(Double curp) {
        this.curp = curp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column morningp.highp
     *
     * @return the value of morningp.highp
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public Double getHighp() {
        return highp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column morningp.highp
     *
     * @param highp the value for morningp.highp
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public void setHighp(Double highp) {
        this.highp = highp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column morningp.lowp
     *
     * @return the value of morningp.lowp
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public Double getLowp() {
        return lowp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column morningp.lowp
     *
     * @param lowp the value for morningp.lowp
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public void setLowp(Double lowp) {
        this.lowp = lowp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column morningp.curbuyp
     *
     * @return the value of morningp.curbuyp
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public Double getCurbuyp() {
        return curbuyp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column morningp.curbuyp
     *
     * @param curbuyp the value for morningp.curbuyp
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public void setCurbuyp(Double curbuyp) {
        this.curbuyp = curbuyp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column morningp.curslp
     *
     * @return the value of morningp.curslp
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public Double getCurslp() {
        return curslp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column morningp.curslp
     *
     * @param curslp the value for morningp.curslp
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public void setCurslp(Double curslp) {
        this.curslp = curslp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column morningp.curzs
     *
     * @return the value of morningp.curzs
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public Long getCurzs() {
        return curzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column morningp.curzs
     *
     * @param curzs the value for morningp.curzs
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public void setCurzs(Long curzs) {
        this.curzs = curzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column morningp.curamount
     *
     * @return the value of morningp.curamount
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public Double getCuramount() {
        return curamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column morningp.curamount
     *
     * @param curamount the value for morningp.curamount
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public void setCuramount(Double curamount) {
        this.curamount = curamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column morningp.byonesh
     *
     * @return the value of morningp.byonesh
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public Long getByonesh() {
        return byonesh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column morningp.byonesh
     *
     * @param byonesh the value for morningp.byonesh
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public void setByonesh(Long byonesh) {
        this.byonesh = byonesh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column morningp.byonep
     *
     * @return the value of morningp.byonep
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public Double getByonep() {
        return byonep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column morningp.byonep
     *
     * @param byonep the value for morningp.byonep
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public void setByonep(Double byonep) {
        this.byonep = byonep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column morningp.bytwosh
     *
     * @return the value of morningp.bytwosh
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public Long getBytwosh() {
        return bytwosh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column morningp.bytwosh
     *
     * @param bytwosh the value for morningp.bytwosh
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public void setBytwosh(Long bytwosh) {
        this.bytwosh = bytwosh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column morningp.bytwop
     *
     * @return the value of morningp.bytwop
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public Double getBytwop() {
        return bytwop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column morningp.bytwop
     *
     * @param bytwop the value for morningp.bytwop
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public void setBytwop(Double bytwop) {
        this.bytwop = bytwop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column morningp.bythreesh
     *
     * @return the value of morningp.bythreesh
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public Long getBythreesh() {
        return bythreesh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column morningp.bythreesh
     *
     * @param bythreesh the value for morningp.bythreesh
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public void setBythreesh(Long bythreesh) {
        this.bythreesh = bythreesh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column morningp.bythreep
     *
     * @return the value of morningp.bythreep
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public Double getBythreep() {
        return bythreep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column morningp.bythreep
     *
     * @param bythreep the value for morningp.bythreep
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public void setBythreep(Double bythreep) {
        this.bythreep = bythreep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column morningp.byfoursh
     *
     * @return the value of morningp.byfoursh
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public Long getByfoursh() {
        return byfoursh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column morningp.byfoursh
     *
     * @param byfoursh the value for morningp.byfoursh
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public void setByfoursh(Long byfoursh) {
        this.byfoursh = byfoursh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column morningp.byfourp
     *
     * @return the value of morningp.byfourp
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public Double getByfourp() {
        return byfourp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column morningp.byfourp
     *
     * @param byfourp the value for morningp.byfourp
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public void setByfourp(Double byfourp) {
        this.byfourp = byfourp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column morningp.byfivesh
     *
     * @return the value of morningp.byfivesh
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public Long getByfivesh() {
        return byfivesh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column morningp.byfivesh
     *
     * @param byfivesh the value for morningp.byfivesh
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public void setByfivesh(Long byfivesh) {
        this.byfivesh = byfivesh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column morningp.byfivep
     *
     * @return the value of morningp.byfivep
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public Double getByfivep() {
        return byfivep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column morningp.byfivep
     *
     * @param byfivep the value for morningp.byfivep
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public void setByfivep(Double byfivep) {
        this.byfivep = byfivep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column morningp.slonesh
     *
     * @return the value of morningp.slonesh
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public Long getSlonesh() {
        return slonesh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column morningp.slonesh
     *
     * @param slonesh the value for morningp.slonesh
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public void setSlonesh(Long slonesh) {
        this.slonesh = slonesh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column morningp.slonep
     *
     * @return the value of morningp.slonep
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public Double getSlonep() {
        return slonep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column morningp.slonep
     *
     * @param slonep the value for morningp.slonep
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public void setSlonep(Double slonep) {
        this.slonep = slonep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column morningp.sltwosh
     *
     * @return the value of morningp.sltwosh
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public Long getSltwosh() {
        return sltwosh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column morningp.sltwosh
     *
     * @param sltwosh the value for morningp.sltwosh
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public void setSltwosh(Long sltwosh) {
        this.sltwosh = sltwosh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column morningp.sltwop
     *
     * @return the value of morningp.sltwop
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public Double getSltwop() {
        return sltwop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column morningp.sltwop
     *
     * @param sltwop the value for morningp.sltwop
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public void setSltwop(Double sltwop) {
        this.sltwop = sltwop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column morningp.slthreesh
     *
     * @return the value of morningp.slthreesh
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public Long getSlthreesh() {
        return slthreesh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column morningp.slthreesh
     *
     * @param slthreesh the value for morningp.slthreesh
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public void setSlthreesh(Long slthreesh) {
        this.slthreesh = slthreesh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column morningp.slthreep
     *
     * @return the value of morningp.slthreep
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public Double getSlthreep() {
        return slthreep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column morningp.slthreep
     *
     * @param slthreep the value for morningp.slthreep
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public void setSlthreep(Double slthreep) {
        this.slthreep = slthreep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column morningp.slfoursh
     *
     * @return the value of morningp.slfoursh
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public Long getSlfoursh() {
        return slfoursh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column morningp.slfoursh
     *
     * @param slfoursh the value for morningp.slfoursh
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public void setSlfoursh(Long slfoursh) {
        this.slfoursh = slfoursh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column morningp.slfourp
     *
     * @return the value of morningp.slfourp
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public Double getSlfourp() {
        return slfourp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column morningp.slfourp
     *
     * @param slfourp the value for morningp.slfourp
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public void setSlfourp(Double slfourp) {
        this.slfourp = slfourp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column morningp.slfivesh
     *
     * @return the value of morningp.slfivesh
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public Long getSlfivesh() {
        return slfivesh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column morningp.slfivesh
     *
     * @param slfivesh the value for morningp.slfivesh
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public void setSlfivesh(Long slfivesh) {
        this.slfivesh = slfivesh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column morningp.slfivep
     *
     * @return the value of morningp.slfivep
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public Double getSlfivep() {
        return slfivep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column morningp.slfivep
     *
     * @param slfivep the value for morningp.slfivep
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public void setSlfivep(Double slfivep) {
        this.slfivep = slfivep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column morningp.rate
     *
     * @return the value of morningp.rate
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public Double getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column morningp.rate
     *
     * @param rate the value for morningp.rate
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public void setRate(Double rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column morningp.zs
     *
     * @return the value of morningp.zs
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public Long getZs() {
        return zs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column morningp.zs
     *
     * @param zs the value for morningp.zs
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public void setZs(Long zs) {
        this.zs = zs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column morningp.hang
     *
     * @return the value of morningp.hang
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public Boolean getHang() {
        return hang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column morningp.hang
     *
     * @param hang the value for morningp.hang
     *
     * @mbggenerated Wed Sep 30 07:41:25 CST 2015
     */
    public void setHang(Boolean hang) {
        this.hang = hang;
    }
}