package com.springapp.model.database;

import java.util.Date;

public class Weight {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weight.id
     *
     * @mbggenerated Fri Sep 25 10:52:32 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weight.code
     *
     * @mbggenerated Fri Sep 25 10:52:32 CST 2015
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weight.decr
     *
     * @mbggenerated Fri Sep 25 10:52:32 CST 2015
     */
    private Integer decr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weight.day
     *
     * @mbggenerated Fri Sep 25 10:52:32 CST 2015
     */
    private Date day;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weight.value
     *
     * @mbggenerated Fri Sep 25 10:52:32 CST 2015
     */
    private Boolean value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weight.wet
     *
     * @mbggenerated Fri Sep 25 10:52:32 CST 2015
     */
    private Double wet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weight.rate
     *
     * @mbggenerated Fri Sep 25 10:52:32 CST 2015
     */
    private Double rate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weight.incre
     *
     * @mbggenerated Fri Sep 25 10:52:32 CST 2015
     */
    private Integer incre;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weight.id
     *
     * @return the value of weight.id
     *
     * @mbggenerated Fri Sep 25 10:52:32 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weight.id
     *
     * @param id the value for weight.id
     *
     * @mbggenerated Fri Sep 25 10:52:32 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weight.code
     *
     * @return the value of weight.code
     *
     * @mbggenerated Fri Sep 25 10:52:32 CST 2015
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weight.code
     *
     * @param code the value for weight.code
     *
     * @mbggenerated Fri Sep 25 10:52:32 CST 2015
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weight.decr
     *
     * @return the value of weight.decr
     *
     * @mbggenerated Fri Sep 25 10:52:32 CST 2015
     */
    public Integer getDecr() {
        return decr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weight.decr
     *
     * @param decr the value for weight.decr
     *
     * @mbggenerated Fri Sep 25 10:52:32 CST 2015
     */
    public void setDecr(Integer decr) {
        this.decr = decr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weight.day
     *
     * @return the value of weight.day
     *
     * @mbggenerated Fri Sep 25 10:52:32 CST 2015
     */
    public Date getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weight.day
     *
     * @param day the value for weight.day
     *
     * @mbggenerated Fri Sep 25 10:52:32 CST 2015
     */
    public void setDay(Date day) {
        this.day = day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weight.value
     *
     * @return the value of weight.value
     *
     * @mbggenerated Fri Sep 25 10:52:32 CST 2015
     */
    public Boolean getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weight.value
     *
     * @param value the value for weight.value
     *
     * @mbggenerated Fri Sep 25 10:52:32 CST 2015
     */
    public void setValue(Boolean value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weight.wet
     *
     * @return the value of weight.wet
     *
     * @mbggenerated Fri Sep 25 10:52:32 CST 2015
     */
    public Double getWet() {
        return wet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weight.wet
     *
     * @param wet the value for weight.wet
     *
     * @mbggenerated Fri Sep 25 10:52:32 CST 2015
     */
    public void setWet(Double wet) {
        this.wet = wet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weight.rate
     *
     * @return the value of weight.rate
     *
     * @mbggenerated Fri Sep 25 10:52:32 CST 2015
     */
    public Double getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weight.rate
     *
     * @param rate the value for weight.rate
     *
     * @mbggenerated Fri Sep 25 10:52:32 CST 2015
     */
    public void setRate(Double rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weight.incre
     *
     * @return the value of weight.incre
     *
     * @mbggenerated Fri Sep 25 10:52:32 CST 2015
     */
    public Integer getIncre() {
        return incre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weight.incre
     *
     * @param incre the value for weight.incre
     *
     * @mbggenerated Fri Sep 25 10:52:32 CST 2015
     */
    public void setIncre(Integer incre) {
        this.incre = incre;
    }
}